# Replace rust-ci with your binary name.
name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: cargo fmt -- --check
        run: cargo fmt --all -- --check


  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features: [ default, std ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: cargo clippy
        run: cargo clippy --features ${{ matrix.features }} -- -D warnings


  test:
    name: Test
    needs: [ style, clippy ]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build: [ stable ]
        features: [ default, std ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build debug
        run: cargo build --features ${{ matrix.features }}

      - name: Test
        run: cargo test ${{ matrix.features }}

  create-release:
    name: deploy
    needs: [ test ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, i686-unknown-linux-gnu, i686-unknown-linux-musl, mips-unknown-linux-gnu, mips64-unknown-linux-gnuabi64, mips64el-unknown-linux-gnuabi64, mipsel-unknown-linux-gnu, powerpc-unknown-linux-gnu, powerpc64-unknown-linux-gnu, powerpc64le-unknown-linux-gnu,           arm-unknown-linux-gnueabi          ,x86_64-unknown-linux-gnu           ,x86_64-unknown-linux-musl ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        run: cargo install cross --locked

      - name: Build target
        run: cross build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          # TODO:
          # strip target/${{ matrix.target }}/release/vfat-rs

          cd target/${{ matrix.target }}/release          
          tar czvf ../../../vfat-rs-${{ matrix.target }}.tar.gz vfat-rs
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v2
        # TODO: if any of the build step fails, the release should be deleted.
        with:
          files: 'vfat-rs*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

